@startuml

title __OBJECTP MP's Class Diagram__\n

  package model {
    class Apple {
    }
  }
  

  package model {
    class Banana {
    }
  }
  

  package model {
    class Carrot {
    }
  }
  

  package model {
    class Constants {
    }
  }
  

  package model {
    abstract class Crop {
    }
  }
  

  package model {
    class Fertilizer {
    }
  }
  

  package model {
    abstract class FiniteItem {
    }
  }
  

  package model {
    class Game {
    }
  }
  

  package app {
    class GameController {
    }
  }
  

  package app {
    class GameWindow {
    }
  }
  

  package app {
    class InventoryPanel {
    }
  }
  

  package model {
    abstract class Item {
    }
  }
  

  package app {
    class LotPanel {
    }
  }
  

  package model {
    class Mango {
    }
  }
  

  package app {
    class Menu {
    }
  }
  

  package model {
    class Orange {
    }
  }
  

  package model {
    class Player {
    }
  }
  

  package app {
    class PlayerPanel {
    }
  }
  

  package model {
    class Potato {
    }
  }
  

  package model {
    class Rose {
    }
  }
  

  package model {
    class Seed {
    }
  }
  

  package app {
    class ShopPanel {
    }
  }
  

  package model {
    class Stargazer {
    }
  }
  

  package model {
    class Sunflower {
    }
  }
  

  package model {
    class Tile {
    }
  }
  

  package model {
    class Tomato {
    }
  }
  

  package model {
    class Tulip {
    }
  }
  

  package model {
    class Turnip {
    }
  }
  

  Apple -up-|> Crop
  Banana -up-|> Crop
  Carrot -up-|> Crop
  Crop o-- CropName : name
  Crop o-- CropType : type
  Crop o-- CropStatus : status
  Fertilizer -up-|> FiniteItem
  FiniteItem -up-|> Item
  FiniteItem o-- FiniteItemType : type
  Game o-- Player : player
  GameController o-- GameWindow : window
  GameController o-- Game : model
  GameWindow -up-|> JFrame
  GameWindow o-- PlayerPanel : player
  GameWindow o-- LotPanel : lot
  GameWindow o-- InventoryPanel : inventory
  GameWindow o-- ShopPanel : shop
  InventoryPanel -up-|> ActionListener
  InventoryPanel -up-|> JPanel
  LotPanel -up-|> ActionListener
  LotPanel -up-|> JPanel
  Mango -up-|> Crop
  Menu -up-|> ActionListener
  Menu -up-|> JFrame
  Orange -up-|> Crop
  Player o-- Fertilizer : fertilizer
  PlayerPanel -up-|> JPanel
  Potato -up-|> Crop
  Rose -up-|> Crop
  Seed -up-|> FiniteItem
  Seed o-- CropName : seed
  ShopPanel -up-|> ActionListener
  ShopPanel -up-|> JPanel
  Stargazer -up-|> Crop
  Sunflower -up-|> Crop
  Tile o-- TileStatus : status
  Tile o-- Crop : crop
  Tomato -up-|> Crop
  Tulip -up-|> Crop
  Turnip -up-|> Crop


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
